### ISSUE TITLE
Can the Operator commit the zero hash safely for empty blocks?

### ISSUE THREAD

**Issue by karlfloersch** [plasma-group/plasma-contracts#12]
When a chain is just starting up it is useful to commit empty blocks. This is because deposits must only be available in *the next* block after they are submitted (I believe). Can the operator commit the zero hash (32 bytes of 0's) to signify a block which is empty? I believe this is the case but just want to sanity check.

@ben-chain am I right here? Am I right that committing empty blocks isn't a bad idea?

**Comment by kfichter** [comment]
> This is because deposits must only be available in the *next* block after they are submitted

Hmmm why is this? If the latest block is `Block 0` and I submit a deposit, am I unable to spend in `Block 1`?

> Can the operator commit the zero hash (32 bytes of 0's) to signify a block which is empty?

Yes I don't believe this is problematic, as long as clients know that the zero hash signifies an empty block. We'd be in a lot of trouble if someone could fake the zero hash.

**Comment by ben-chain** [comment]
Yep, this definitely works--specifically, all exits from that `blockNumber` would have no response to `challengeInclusion()`s.

 Ditto to Kelvin's question though, feels like deposits should be spendable as early as the next ethereum block.

**Comment by karlfloersch** [comment]
> Hmmm why is this? If the latest block is Block 0 and I submit a deposit, am I unable to spend in Block 1?

Hmm.... good question! I felt like while in Bangkok I came to the conclusion that it was needed but at this point I can't come up with a reason for it. I think you're right that you should be able to transact immediately after depositing (& finality).

I'll close this for now then.
