### ISSUE TITLE
Smart Contract Naming

### ISSUE THREAD

**Issue by karlfloersch** [plasma-group/plasma-contracts#16]
There are two main smart contracts which we need:
1. A plasma chain factory contract
2. A plasma chain contract itself

The factory will manage the creation of new plasma chains which includes ensuring everyone is using the correct plasma contract code, and holding a registry of known plasma chains which can be explored.

The plasma contract will manage deposits & exits & all things related to what we normally think of as Plasma. 

What should the names of these contracts be? My current favorite is probably:
```
PlasmaNetwork.vy
PlasmaChain.vy
```

But other possibilities are:
```
PlasmaFactory.vy
Plasma.vy

PlasmaNetworkFactory.vy
PlasmaChain.vy
...
etc
```

What do yall think?

**Comment by ben-chain** [comment]
I'll throw out out `PlasmaRegistry.vy` as an alternative.  I think `PlasmaChain.vy` is good for the main contract.

**Comment by karlfloersch** [comment]
Ah that's good!

**Comment by karlfloersch** [comment]
Right now leaning towards `PlasmaRegistry.vy`--seems more descriptive. I'll just roll with that for now

**Comment by karlfloersch** [comment]
Closing for now though @kfichter feel free to weigh in <3
