### ISSUE TITLE
Setup function doesn't block users from calling the function twice

### ISSUE THREAD

**Issue by kfichter** [plasma-group/plasma-contracts#31]
`setup()` is used to initialize the contract instead of a constructor. However, it currently doesn't block a user from calling the function twice, so anyone could call `setup()` again and wipe the contract.

https://github.com/plasma-group/plasma-contracts/blob/70655cf0a4298f9ff4925b08cbbc89fd1e8af784/contracts/PlasmaChain.vy#L447-L455

**Comment by ben-chain** [comment]
Great catch!  That would've been bad.

Will be fixed in the next PR merge, I actually happened to stumble across this too when modifying for ERC20 support.
